python train.py \
    --ours \
    --no_tags_gene \
    --train_vanilla \
    --dataset=cmnist \
    --percent=5pct \
    --lr=0.01 \
    --data_dir '/home/zungwooker/Debiasing/benchmarks' \
    --preproc_dir '/home/zungwooker/Debiasing/preproc' \
    --projcode 'CMNIST 5pct' \
    --run_name 'vanilla-ours-no-tags-gene' \
    --device 'cuda' \
    --gpu_num 3 \
    --fix_randomseed \
    --seed 0 \
    --wandb

python train.py \
    --ours \
    --no_tags_gene \
    --train_vanilla \
    --dataset=cmnist \
    --percent=5pct \
    --lr=0.01 \
    --data_dir '/home/zungwooker/Debiasing/benchmarks' \
    --preproc_dir '/home/zungwooker/Debiasing/preproc' \
    --projcode 'CMNIST 5pct' \
    --run_name 'vanilla-ours-no-tags-gene' \
    --device 'cuda' \
    --gpu_num 3 \
    --fix_randomseed \
    --seed 42 \
    --wandb