python train.py \
    --ours \
    --half_generated \
    --train_lff \
    --dataset=cmnist \
    --percent=1pct \
    --lr=0.01 \
    --data_dir '/home/zungwooker/Debiasing/benchmarks' \
    --preproc_dir '/home/zungwooker/Debiasing/preproc' \
    --projcode 'CMNIST 1pct' \
    --run_name 'LfF-ours' \
    --device 'cuda' \
    --gpu_num 1 \
    --fix_randomseed \
    --seed 0 \
    --wandb

python train.py \
    --ours \
    --half_generated \
    --train_lff \
    --dataset=cmnist \
    --percent=1pct \
    --lr=0.01 \
    --data_dir '/home/zungwooker/Debiasing/benchmarks' \
    --preproc_dir '/home/zungwooker/Debiasing/preproc' \
    --projcode 'CMNIST 1pct' \
    --run_name 'LfF-ours' \
    --device 'cuda' \
    --gpu_num 1 \
    --fix_randomseed \
    --seed 42 \
    --wandb