wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722840994.755125
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.9.0
      5: 0.16.3
      8:
      - 6
      13: linux-x86_64
    m:
    - 1: Iter step
    - 1: valid/accs_b
      5: 1
      6:
      - 1
    - 1: valid/accs_d
      5: 1
      6:
      - 1
    - 1: test/accs_b
      5: 1
      6:
      - 1
    - 1: test/accs_d
      5: 1
      6:
      - 1
    - 1: valid/best_acc_b
      5: 1
      6:
      - 1
    - 1: valid/best_acc_d
      5: 1
      6:
      - 1
    - 1: test/best_acc_b
      5: 1
      6:
      - 1
    - 1: test/best_acc_d
      5: 1
      6:
      - 1
